export const supriseMePrompts = [
  'A serene forest with glowing mushrooms and bioluminescent trees under a starry night sky.',
  'A futuristic city built into the side of a massive cliff overlooking the ocean.',
  'A surreal desert with floating islands and waterfalls cascading into the void.',
  'A crystal-clear lake reflecting a double moon in a distant galaxy.',
  'A lush jungle with ancient ruins overgrown with vines and exotic flowers.',
  'A dragon made entirely of flowers, soaring over a medieval castle.',
  'A futuristic knight with a glowing sword battling a robotic beast in a neon-lit arena.',
  'A mermaid with iridescent scales lounging on a rock in a stormy ocean.',
  'A phoenix rising from the ashes, its feathers made of fire and gold.',
  'A wizard’s tower floating in the clouds, surrounded by magical creatures.',
  'A cyberpunk cityscape with flying cars, neon signs, and rain-soaked streets.',
  'A spaceship landing on an alien planet with three suns and strange vegetation.',
  'A robot with a human-like face, sitting in a field of sunflowers.',
  'A futuristic utopia where nature and technology coexist harmoniously.',
  'A dystopian wasteland with abandoned skyscrapers and a lone survivor.',
  'A majestic wolf with glowing blue eyes standing on a snowy mountain peak.',
  'A hybrid creature: half-eagle, half-lion, flying through a stormy sky.',
  'A swarm of butterflies forming the shape of a human face.',
  'A giant turtle with an entire ecosystem on its back, swimming in the ocean.',
  'A cat with galaxy-like fur, sitting on a windowsill overlooking a futuristic city.',
  'A melting clock draped over a tree branch in a dreamlike landscape.',
  'A floating island with a waterfall that flows upward into the sky.',
  'A human figure made entirely of shattered glass, reflecting a rainbow of colors.',
  'A labyrinth of doors floating in space, each leading to a different dimension.',
  'A giant hand reaching out of the ocean, holding a glowing orb.',
  'A samurai standing on a bridge in the rain, surrounded by cherry blossoms.',
  'An ancient Egyptian pharaoh in a futuristic spaceship.',
  'A Viking longship sailing through a sea of stars.',
  'A Renaissance-style painting of a modern-day city.',
  'A traditional Japanese tea house surrounded by a futuristic metropolis.',
  'A candyland world where everything is made of sweets and chocolate.',
  'A teddy bear wearing a spacesuit, exploring the surface of Mars.',
  'A group of penguins having a tea party on an iceberg.',
  'A giant cupcake with a cherry on top, sitting in the middle of a city square.',
  'A squirrel wearing a tiny crown, ruling over a forest kingdom.',
  'A haunted mansion surrounded by twisted trees and a full moon.',
  'A shadowy figure standing in a foggy graveyard, holding a lantern.',
  'A post-apocalyptic city overrun by vines and wild animals.',
  'A dark forest with glowing red eyes peering from the shadows.',
  'A lone figure walking through a deserted carnival at night.',
  'A cozy cabin in the woods covered in snow, with smoke rising from the chimney.',
  'A pumpkin patch under a harvest moon, with scarecrows coming to life.',
  'A beach scene with palm trees decorated for Christmas.',
  'A field of tulips in spring, with a rainbow stretching across the sky.',
  'A spooky Halloween scene with ghosts, witches, and jack-o’-lanterns.',
  'A steampunk airship flying over a Victorian-era city.',
  'A library with infinite shelves, floating in outer space.',
  'A giant hourglass with galaxies instead of sand.',
  'A surreal portrait of a person with a galaxy inside their head.',
  'A futuristic train speeding through a tunnel of light and colors.',
];
